PREFIX dbpedia-owl: <http://dbpedia.org/ontology#>  
PREFIX ogc: <http://www.opengis.net/ont/geosparql#>
PREFIX geom: <http://geovocab.org/geometry#>
PREFIX lgdo: <http://linkedgeodata.org/ontology/>

SELECT ?id ?name (strafter(str(?amenity),'ontology/') as ?amenityName) ?geometry 
		WHERE {  
			?amenityNode a ?amenity .  
			?amenityNode lgdo:id ?id .
        	?amenityNode geom:geometry ?geometryNode .
        	?geometryNode ogc:asWKT ?geometry .
        	OPTIONAL {?amenityNode lgdo:name ?name}
		}
